### ISSUE TITLE
Network trained with train-stream cannot be exported to JSON

### ISSUE THREAD

**Issue by Vectorrent** [BrainJS/train-stream#1]
When I instantiate a GRU/LSTM network, I can use the .toJSON() method without issue. When I train with vanilla Brain.js, I can also export without issue.

When I train with train-stream, the network cannot be exported. There are two errors I keep running into.

This one happens while running in the main thread:
```
one-brain-1  | RangeError: Maximum call stack size exceeded
one-brain-1  |     at GRU.toJSON (/one/node_modules/brain.js/dist/index.js:7632:11)
one-brain-1  |     at JSON.stringify (<anonymous>)
one-brain-1  |     at file:///one/src/encoder.js:79:46
```
And this one happens in a worker:
```
one-brain-1   | node:internal/event_target:1037
one-brain-1   |   process.nextTick(() => { throw err; });
one-brain-1   |                            ^
one-brain-1   | 
one-brain-1   | RangeError [Error]: Maximum call stack size exceeded
one-brain-1   |     at GRU.toJSON (/one/node_modules/brain.js/dist/index.js:7632:11)
one-brain-1   |     at JSON.stringify (<anonymous>)
one-brain-1   |     at MessagePort.<anonymous> (file:///one/src/encoder.js:36:50)
one-brain-1   |     at [nodejs.internal.kHybridDispatch] (node:internal/event_target:762:20)
one-brain-1   |     at exports.emitMessage (node:internal/per_context/messageport:23:28)
one-brain-1   | Emitted 'error' event on Worker instance at:
one-brain-1   |     at [kOnErrorMessage] (node:internal/worker:326:10)
one-brain-1   |     at [kOnMessage] (node:internal/worker:337:37)
one-brain-1   |     at MessagePort.<anonymous> (node:internal/worker:232:57)
one-brain-1   |     at [nodejs.internal.kHybridDispatch] (node:internal/event_target:762:20)
one-brain-1   |     at exports.emitMessage (node:internal/per_context/messageport:23:28)
one-brain-1   | 
one-brain-1   | Node.js v20.3.1
```
Node 18 fails with the same error. I'm not sure how to proceed at this point. 

On a different note, will this run in the browser? And if not, are there any plans to bring the functionality?

**Comment by Vectorrent** [comment]
Well, as it turned out, it is not the toJSON() method causing the crash, but JSON.stringify(). Even when the network is objectively tiny (just [3, 3] hidden layers), trying to `JSON.stringify(net.toJSON())` will hang the thread for about 30 seconds, before reaching the maximum call stack size. I suspect I'll be able to find a workaround, but this is still rather odd and annoying.

**Comment by Vectorrent** [comment]
I'm not really sure what changed, but I am able to save a network with train-stream now. I suspect maybe I was running into some resource constraints, or something. Anyway, I'm going to close this issue now.
